create table
  public.roster (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name text null,
    _email text null,
    rank text null default 'Firefighter'::text,
    isProbationary boolean null default false,
    userId uuid null,
    constraint Roster_pkey primary key (id),
    constraint roster_userId_fkey foreign key (userId) references auth.users (id) on delete set null
  ) tablespace pg_default;

create table
  public.agencies (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name character varying null,
    code character varying null,
    constraint agencies_pkey primary key (id),
    constraint agencies_code_key unique (code)
  ) tablespace pg_default;

create table
  public.reports (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    firstName character varying null,
    lastName character varying null,
    typeIssue character varying null,
    issueDescription character varying null,
    personInvolved bigint null,
    constraint reports_pkey primary key (id),
    constraint reports_personInvolved_fkey foreign key (personInvolved) references roster (id) on delete set null
  ) tablespace pg_default;

create table
  public.reportIssueTypes (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    name text null,
    slug text null
  ) tablespace pg_default;
